```{r modelhalf, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
library(cmdstanr)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Model half

In this chapter we sample the selected model with half data

## Data

```{r datahalflim, echo=T}
dist_edge <- 20
n_census <- 10
n_ind_species <- 10
```

```{r datahalf, eval=F}
guyafor <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
trees <- tbl(guyafor, "inventory") %>% 
  filter(Forest == "Paracou") %>% 
  filter(Xfield > local(dist_edge), Xfield < 250-local(dist_edge), 
         Yfield > local(dist_edge), Yfield < 250-local(dist_edge)) %>% 
  mutate(species = paste(Genre, Espece)) %>% 
  collect() %>% 
  filter(!grepl("Indet", species)) %>% 
  filter(BotaSource == "Bota") %>% 
  group_by(idTree) %>% 
  arrange(CensusYear) %>% 
  mutate(FirstDead = first(CensusYear[CodeAlive == 0])) %>% 
  mutate(FirstDead = ifelse(is.na(FirstDead), max(CensusYear)+1, FirstDead)) %>% 
  filter(CensusYear < FirstDead) %>% 
  ungroup() %>% 
  mutate(DBH = CircCorr/pi) %>% 
  group_by(idTree) %>% 
  filter(n() > n_census) %>% 
  group_by(species) %>% 
  filter(length(unique(idTree)) > n_ind_species)
DBI::dbDisconnect(guyafor) ; rm(guyafor, dist_edge, n_census, n_ind_species)
dplyr::select(trees, species, idTree) %>% 
  unique() %>% 
  group_by(species) %>% 
  sample_n(20, replace = T) %>% 
  unique() %>% 
  left_join(trees) %>% 
  vroom::vroom_write("save/trees_half.tsv")
```

```{r datahalftab}
options(knitr.kable.NA = '')
vroom::vroom("save/trees_half.tsv") %>% 
  group_by(Family, Genus, species, idTree) %>% 
  summarise(census = n(), year_start = min(CensusYear), year_end = max(CensusYear),
            dbh_start = min(DBH), dbh_end = max(DBH)) %>% 
  ungroup() %>% 
  summarise(n_families = length(unique(Family)),
            n_genera = length(unique(Genus)),
            n_species = length(unique(species)),
            n_individuals = length(unique(idTree)),
            n_observations = nrow(vroom::vroom("save/trees_half.tsv")),
            min_census = min(census),
            med_census = median(census),
            max_census = max(census),
            min_year0 = min(year_start),
            med_year0 = median(year_start),
            max_year0 = max(year_start),
            min_yearmax = min(year_end),
            med_yearmax = median(year_end),
            max_yearmax = max(year_end),
            min_dbh0 = min(dbh_start),
            med_dbh0 = median(dbh_start),
            max_dbh0 = max(dbh_start),
            min_dbhmax = min(dbh_end),
            med_dbhmax = median(dbh_end),
            max_dbhmax = max(dbh_end)) %>% 
  reshape2::melt() %>% 
  separate(variable, c("measure", "variable")) %>% 
  reshape2::dcast(variable ~ measure) %>% 
  dplyr::select(variable, n, med, min, max) %>% 
  mutate(variable = factor(variable, levels = c("families", "genera", "species", "individuals", "observations",
                                                "census", "year0", "yearmax", "dbh0", "dbhmax"))) %>% 
  arrange(variable) %>% 
  kable(col.names = c("", "N", "Median", "Minimum", "Maximum"), format.args = list(big.mark = " "), digits = 0,
        caption = "Metrics on inventory data used to fit the full model including sample size (N), memdian, minimum and maximum values for families, genera, species, individuals, observations, cenusus, recruitment year (year0), last censused year (yearmax), recruitment diameter (dbh0) and last censused diameter (dbhmax).") 
```


```{r mdatahalf, eval=F}
vroom::vroom("save/trees_half.tsv") %>% 
  group_by(idTree) %>% 
  mutate(Year = CensusYear - min(CensusYear)) %>%
  ungroup() %>% 
  mutate(ind = as.numeric(as.factor(as.character(idTree)))) %>% 
  mutate(sp = as.numeric(as.factor(species))) %>% 
  vroom::vroom_write("save/mdatahalf.tsv")
```

```{r mdatahalffig}
dplyr::select(vroom::vroom("save/mdatahalf.tsv"), sp, ind) %>% 
  unique() %>% 
  filter(sp %in% sample(unique(.$sp), 9)) %>% 
  group_by(sp) %>% 
  sample_n(10, replace = T) %>%
  unique() %>% 
  left_join(vroom::vroom("save/mdatahalf.tsv")) %>% 
  ggplot(aes(Year, DBH, group = as.factor(ind))) +
  geom_point(col = "grey") +
  geom_smooth(se = F, aes(col = as.factor(ind))) +
  xlim(0,NA) +
  facet_wrap(~ species, scales = "free") +
  scale_color_discrete(guide = "none") 
```

## Model

Using time $t$ since recruitment (DBH=10cm) for each individual tree $i$ in species $s$:

$$  DBH_{t,i,s} \sim \mathcal N  (10 + gmax_i \times \sum _{y=1 | DBH_{1,i} = DBH_{recruitment}} ^{y=t} exp(-\frac12.[\frac{log(\frac{DBH_{t,i}}{100.Dopt_s})}{Ks_s}]^2)), \sigma)$$

```{r growthhalffit, eval=F}
mdata <- vroom::vroom("save/mdatahalf.tsv")
growth <- cmdstan_model("model/growth.stan")
fit <- growth$sample(
  data = list(
    N = nrow(filter(mdata, Year > 0)),
    I = max(mdata$ind),
    S = max(mdata$sp),
    Y = max(mdata$Year),
    year = filter(mdata, Year > 0)$Year,
    dbh = filter(mdata, Year > 0)$DBH,
    dbh0 = filter(mdata, Year == 0)$DBH,
    ind = filter(mdata, Year > 0)$ind,
    indsp = arrange(unique(mdata[c("ind", "sp")]), ind)$sp
  ),
  chains = 4, 
  parallel_chains = 4,
  refresh = 10,
  save_warmup = F,
  max_treedepth = 12
)
fit$save_output_files(dir = "save/growthhalf")
fit_half <- rstan::read_stan_csv(fit$output_files())
save(fit_half, file = "save/growthhalf.Rdata") 
```

```{r growthhalfsampling, eval=F}
mdata <- vroom::vroom("save/mdatahalf.tsv")
load("save/growthhalf.Rdata")  
# fit_half <- rstan::read_stan_csv(list.files("save/growthhalf/", full.names = T))
```

```{r growthhalfrhat, eval=F}
# mcmc_rhat(rhat(fit_half)) 
```

```{r growthhalftrace, eval=F}
mcmc_trace(as.array(fit_half, pars = c("gmax[1]", "dopt[1]", "ks[1]", "sigma")))
```

```{r growthhalfpairs, eval=F}
mcmc_pairs(as.array(fit_half, pars = c("gmax[1]", "dopt[1]", "ks[1]", "sigma"))) 
```

```{r growthhalfalpha, eval=F}
mcmc_intervals(as.array(fit_half, pars = "gmax"))
```
