```{r analyses, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
library(ggtree)
library(phylosignal)
library(adephylo)
library(ape)
library(phylobase)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Analyses

In this chapter we ...

```{r gmax}
load("save/growthhalf.Rdata")
pars <- as.data.frame(fit_half, pars = c('gmax')) %>%
  reshape2::melt(variable.name = "parameter") %>%
  group_by(parameter) %>%
  summarise(value = median(value)) %>%
  separate(parameter, c("parameter", "ind"), convert = T) %>%
  reshape2::dcast(ind ~ parameter)
rm(fit_half)
mdata <- vroom::vroom("save/mdatahalf.tsv")
pars <- pars %>% 
  left_join(dplyr::select(mdata, ind, idTree, Family, Genus, species, Plot, Xutm, Yutm) %>% unique())
vroom::vroom_write(pars, "save/gmaxhalf.tsv")
```


```{r env, eval=F}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(parallel)
library(doSNOW)
library(foreach)
library(tidyverse)
gmax <- vroom::vroom("save/gmaxhalf.tsv")
cl <- makeCluster(4, outfile = "/dev/null")
registerDoSNOW(cl)
pb <- txtProgressBar(max = nrow(gmax), style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
NC <- foreach(ind=1:nrow(gmax),
              .packages = "dplyr",
              .options.snow = opts) %dopar% {
                con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
                NC <- tbl(con, "inventory") %>% 
                  filter(Plot == local(gmax$Plot[ind])) %>% 
                  filter(idTree != local(gmax$idTree[ind])) %>% 
                  mutate(dij = sqrt((local(gmax$Xutm[ind]) - Xutm)^2+(local(gmax$Yutm[ind]) - Yutm)^2)) %>% 
                  filter(dij < 20) %>% 
                  mutate(DBH = CircCorr/pi) %>% 
                  collect() %>% 
                  group_by(CensusYear) %>% 
                  summarise(NCI = sum(DBH*DBH*exp(-0.25*dij))) %>% 
                  ungroup() %>% 
                  summarise(idTree = local(gmax$idTree[ind]),
                            NCI = mean(NCI))
                DBI::dbDisconnect(con)
                return(NC)
              } 
close(pb)
stopCluster(cl)
NC <- bind_rows(NC)
guyafor <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
trees <- tbl(guyafor, "inventory") %>% 
  filter(Forest == "Paracou") %>% 
  dplyr::select(idTree, Xutm, Yutm) %>% 
  collect() %>% 
  unique()
DBI::dbDisconnect(guyafor) ; rm(guyafor)
XY <- NC %>% 
  left_join(gmax) %>% 
  sf::st_as_sf(coords = c("Xutm", "Yutm"),
             crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
NC$twi <- raster::extract(raster::raster("data/TWI_1m.tif"), XY)
write_tsv(NC, file = "save/env_half.tsv")
```

```{r phylo, eval=F}
library(V.PhyloMaker)
gmax <- vroom::vroom("save/gmaxhalf.tsv")
splist <- gmax %>% 
  dplyr::select(Family, Genus, species) %>% 
  unique() %>% 
  mutate(genus = Genus, family = Family) %>% 
  dplyr::select(species, genus, family)
tree <- phylo.maker(sp.list = splist, tree = GBOTB.extended, nodes = nodes.info.1, scenarios = "S3")
ape::write.tree(tree$scenario.3, "save/phylogeny_half.tree")
```

```{r parsan, eval=F}
vroom::vroom("save/gmaxhalf.tsv") %>% 
  left_join(vroom::vroom(file = "save/env_half.tsv")) %>% 
  unique() %>% 
  vroom::vroom_write(file = "save/growthhalf.tsv")
```

```{r dataan}
growth <- vroom::vroom("save/growthhalf.tsv")
phylo <- ape::read.tree("save/phylogeny_half.tree")
p4d <- phylo4d(phylo,
               data.frame(species = gsub("_", " ", phylo$tip.label)) %>% 
                 left_join(group_by(growth, species) %>% summarise(gmax  = mean(log(gmax), na.rm = T))) %>% 
                 dplyr::select(-species)) 
```

```{r }
lme4::lmer(log(gmax) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), growth) %>% 
  sjPlot::tab_model(show.icc = F) 
```

```{r, eval=F}
m <- lme4::lmer(log(gmax) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), 
                na.omit(dplyr::select(growth, Family, Genus, species, NCI, twi, gmax)) %>% mutate(twi = ifelse(twi <= 0, 10^-6, twi)))
r2 <- partR2::partR2(m, partvars = c("log(NCI)", "log(twi+1)"), R2_type = "marginal", nboot = 10)
partR2::forestplot(r2, type = "R2", text_size = 10)
```

```{r }
ggplot(growth, aes(log(NCI), log(gmax), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none") 
```

```{r }
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(group_by(growth, species) %>% summarise(gmax = mean(gmax))) %>% 
  ggtree(aes(color = log(gmax)), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  viridis::scale_color_viridis(expression(log(gmax)))
```

```{r }
phyloSignal(p4d = p4d, method = "all") %>% 
  lapply(as.data.frame) %>% 
  lapply(rownames_to_column, "parameter") %>% 
  bind_rows(.id = "type") %>% 
  reshape2::melt(c("type", "parameter")) %>% 
  reshape2::dcast(parameter + variable ~ type) %>% 
  kable(caption = "Phylogenetic signal with different methods.")
```

```{r correlog, eval=F}
crlg <- phyloCorrelogram(p4d, trait = "gmax", ci.bs	= 100)
plot(crlg, main="phylogenetic correlogram")
```

```{r lipa}
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(lipaMoran(p4d)$p.value %>% 
              as.data.frame() %>% 
              rownames_to_column("species") %>% 
              mutate(species = gsub("_", " ", species)) %>% 
              dplyr::rename(pval = gmax)) %>% 
  ggtree(aes(color = pval < 0.5), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  scale_color_manual("gamma p<0.05", values =  c("grey", "red", "grey"))
```
