```{r setupgrowthfullgreta, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
library(greta)
library(ggtree)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Growth greta Full

\begin{equation} 
  DBH_{y=today,s,i}  - DBH_{y=y0,s,i} \sim \\
  \mathcal{logN} (log(\theta_{1,s} \times \sum _{y=y_0} ^{y=today} exp(-\frac12.[\frac{log(\frac{DBH_{y,s,i}}{100.\theta_{2,s}})}{\theta_{3,s}}]^2)), \sigma_1) \\ 
  ~ \\
  (\theta_{1,s}, \theta_{2,s}, \theta_{3,s}) \sim \mathcal{logN}^{3 \times S}(log(1),1) \\ 
  \sigma \sim \mathcal{N}_T(0,1) \\ 
  ~ \\
  \theta_{1,s,i} = \frac{DBH_{y=today,s,i}}{\sum_{y=y0}^{y=2020} exp(-\frac12.[\frac{log(\frac{DBH_{y,s,i}}{100.\theta_{2,s}})}{\theta_{3,s}}]^2)} \\ 
    (\#eq:gmax4)
\end{equation} 

```{r samplinggretafull, eval=F}
load("save/mdata_full.Rdata")

# variables & priors
thetas <- lognormal(0, 1, dim = c(mdata$S, 3), truncation = c(0, 3))
sigma <- normal(0, 1, truncation = c(0, Inf))

# predictor
Sigma <- rep(1, mdata$I)
for(t in 1:mdata$Y) {
  Sigma[mdata$Y0 == mdata$years[t]] <- mdata$DBH0[mdata$Y0 == mdata$years[t]]
  Sigma <- Sigma + exp(-0.5* (log(Sigma / (100*thetas[mdata$species,2])) / thetas[mdata$species,3])^2)
}
Sigma <- Sigma - mdata$DBH0

# likelihood
DeltaDBH <- mdata$DBHtoday - mdata$DBH0
distribution(DeltaDBH) <- lognormal(log(thetas[mdata$species,1]*Sigma), sigma)

# generate quantities
thetai <- mdata$DBHtoday / Sigma

# model
m <- model(thetai, thetas, sigma)

# sampling
fit <- mcmc(m, warmup = 1000, n_samples = 1000, chains = 2)

save(data, mdata, fit, file = "save/gmax_greta_full.Rdata")
```

```{r fitgretafull}
load("save/gmax_greta_full.Rdata") 
```

```{r traceplotgretafullsp1, fig.cap="Trace plot sp1."}
sp <- 1
mcmc_trace(fit, pars = c(paste0("thetas[", sp, ",1]"), 
                         paste0("thetas[", sp, ",2]"), 
                         paste0("thetas[", sp, ",3]"), 
                         "sigma")) 
```

```{r traceplotgretafullsp3, fig.cap="Trace plot sp3."}
sp <- 3
mcmc_trace(fit, pars = c(paste0("thetas[", sp, ",1]"), 
                         paste0("thetas[", sp, ",2]"), 
                         paste0("thetas[", sp, ",3]"), 
                         "sigma")) 
```

```{r pairgretafull, fig.cap="Pairs plot."}
mcmc_pairs(fit, pars = c("thetas[1,1]", "thetas[1,2]", "thetas[1,3]", "sigma")) 
```

```{r thetasgretafull, fig.cap="Posteriors for species growth potentials."}
mcmc_intervals(fit, pars = paste0("thetas[", 1:mdata$S, ",1]")) 
```

```{r thetaigretafull, fig.cap="Posteriors for individual growth potentials."}
mcmc_intervals(fit, pars = paste0("thetai[", 1:mdata$I, ",1]")) +
  theme(axis.text.y = element_blank()) 
```

```{r growthgretafulldata, eval=F}
load("save/gmax_stan_full.Rdata") 
data$Gmaxi <- mcmc_intervals_data(fit, pars = paste0("thetai[", 1:mdata$I, ",1]"))$m
data <- left_join(data, 
          data.frame(speciesNum = 1:mdata$S, 
                     Gmaxs = mcmc_intervals_data(fit, pars = paste0("thetai[", 1:mdata$S, ",1]"))$m))
data <- data %>% 
  left_join(read_tsv(file = "save/env_full.tsv"))
vroom::vroom_write(data, "save/growth_greta_full.tsv")
```

```{r datagretafull}
growth <- vroom::vroom("save/growth_greta_full.tsv", show_col_types = F)
phylo <- ape::read.tree("save/phylogeny_full.tree")
```

```{r lmmgretafull}
lme4::lmer(log(Gmaxi) ~ log(NCI) + (1  | Family/Genus/species), growth) %>% 
  sjPlot::tab_model(show.icc = F)
```

```{r NCIgretafull}
ggplot(growth, aes(log(NCI), log(Gmaxi), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```

```{r phylofiggretafull, fig.cap="Species phylogeny. The color indicate the median of the species growth potential (Gmaxs)."}
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(growth) %>% 
  ggtree(aes(color = Gmaxs), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  viridis::scale_color_viridis(expression(Gmax[s]))
```
