```{r genres, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Genetic ressources

```{r species}
species <- vroom::vroom("save/trees_full.tsv") %>% 
  select(Family, Genus, Species) %>% 
  unique() %>% 
  mutate(organism = paste(Genus, Species))
```


```{r genomes}
vroom::vroom("data/eukaryotes_genomes.csv") %>% 
  rename(organism = `#Organism Name`) %>% 
  filter(organism %in% species$organism) %>% 
  select(organism, BioSample, Level, `Size(Mb)`, Scaffolds) %>% 
  kable(caption = "Available genomes from NCBI.")
```

```{r assembly}
vroom::vroom("data/assembly_plants.tsv") %>%
  filter(SpeciesName %in% species$organism) %>% 
  select(AssemblyName, Organism) %>% 
  kable(caption = "Available assembly from NCBI.")
```

```{r sra}
# XML::xmlToDataFrame("data/sra_plants.xml") %>% 
#   filter(SpeciesName %in% species$organism) %>% 
#   kable(caption = "Available SRA from NCBI.")
```

