```{r mm, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
library(greta)
library(ggtree)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Michaelis Menten

Using time $t$ since recruitment (DBH=10cm) for each individual tree $i$:

$$DBH_{i,t} \sim \mathcal N (10 + \frac{\alpha_i \times t}{\beta_i+t}, \sigma)$$

```{r mmdata}
guyafor <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
trees <- tbl(guyafor, "inventory") %>% 
  filter(Forest == "Paracou") %>% 
  # filter(Plot %in% 1:12) %>%
  collect() %>% 
  filter(Xfield > 20, Xfield < 250-20, Yfield > 20, Yfield < 250-20) %>% 
  mutate(species = paste(Genre, Espece)) %>% 
  filter(!grepl("Indet", species)) %>% 
  mutate(DBH = CircCorr/pi)
DBI::dbDisconnect(guyafor) ; rm(guyafor)
```

```{r mmfig}
trees %>% 
  group_by(Plot) %>% 
  mutate(StartYear = min(CensusYear)) %>% 
  group_by(idTree) %>% 
  arrange(CensusYear) %>% 
  filter(first(CensusYear) > StartYear) %>% 
  filter(first(DBH) < 12) %>% 
  filter(last(DBH) > first(DBH)) %>% 
  filter(n() > 20) %>% 
  filter(idTree %in% sample(unique(.$idTree), 20)) %>%
  ggplot(aes(CensusYear, DBH, col = as.factor(idTree))) +
  geom_point(alpha = 0.1) +
  geom_smooth(se = F, alpha = 0.5) +
  scale_y_sqrt() +
  scale_color_discrete(guide = "none")
```

```{r mmmdata}
trees <- trees %>% 
  group_by(Plot) %>% 
  mutate(StartYear = min(CensusYear)) %>% 
  group_by(idTree) %>% 
  arrange(CensusYear) %>% 
  filter(first(CensusYear) > StartYear) %>% 
  filter(first(DBH) < 12) %>% 
  filter(last(DBH) > first(DBH)) %>% 
  filter(n() > 20) %>% 
  mutate(Year = CensusYear - first(CensusYear)) %>%
  ungroup() %>% 
  # filter(idTree %in% sample(unique(.$idTree), 10)) %>%
  mutate(ind = as.numeric(as.factor(as.character(idTree))))
eval <- trees %>% 
  group_by(idTree) %>% 
  filter(CensusYear == max(CensusYear))
mdata <- trees %>% 
  group_by(idTree) %>% 
  filter(CensusYear != max(CensusYear))
```

```{r mmmdatafig}
ggplot(mdata, aes(Year, DBH, col = as.factor(ind))) +
  geom_point() +
  geom_point(data = eval, col = "red", size = 2) +
  geom_smooth(se = F) +
  scale_color_discrete(guide = "none")
```

```{r mmfit, eval=F}
alpha <- normal(0, 10, dim = max(mdata$ind), truncation = c(0, 200))
beta <- normal(0, 10, dim = max(mdata$ind), truncation = c(0, Inf))
sigma <- normal(0, 10, truncation = c(0, 200))
distribution(mdata$DBH) <- normal(10 + alpha[mdata$ind]*mdata$Year/(beta[mdata$ind]+mdata$Year), sigma)
m <- model(alpha, beta, sigma)
fit <- mcmc(m, warmup = 1000, n_samples = 1000, chains = 2)
save(mdata, fit, file = "save/mm.Rdata")
```

```{r mmsapling}
load("save/mm.Rdata") 
```

```{r traceplotmmi1, fig.cap="Trace plot i1."}
ind <- 1
mcmc_trace(fit, pars = c(paste0("alpha[", ind, ",1]"), 
                         paste0("beta[", ind, ",1]"),
                         "sigma")) 
```

```{r pairsplotmmi1, fig.cap="Pairs plot i1."}
ind <- 1
mcmc_pairs(fit, pars = c(paste0("alpha[", ind, ",1]"), 
                         paste0("beta[", ind, ",1]"),
                         "sigma")) 
```

```{r mmrhat, fig.cap="Rhat distribution.", eval=F}
data.frame(Rhat = coda::gelman.diag(fit)$psrf[,1], par = names(coda::gelman.diag(fit)$psrf[,1])) %>% 
  ggplot(aes(Rhat)) +
  geom_histogram()
```

```{r mmalpha, fig.cap="Posteriors for individual plateau."}
mcmc_intervals(fit, regex_pars = "alpha")
```

```{r mmbeta, fig.cap="Posteriors for individual slope."}
mcmc_intervals(fit, regex_pars = "beta")
```

```{r mmpreds, fig.cap="Predictions for individual growth."}
pars <- as.data.frame(summary(fit)$statistics) %>% 
  dplyr::select(Mean) %>% 
  rownames_to_column("parameter") %>% 
  separate(parameter, c("parameter", "ind"), convert = T) %>% 
  reshape2::dcast(ind ~ parameter, value.var = "Mean") %>% 
  dplyr::select(-sigma) 
preds <- pars %>% 
  mutate(Year = list(seq(0, max(trees$Year), length.out = 100))) %>% 
  unnest(Year) %>% 
  mutate(DBH = 10+alpha*Year/(beta+Year))
ggplot(left_join(mdata, pars), aes(Year, DBH, col = log(beta), group = ind)) +
  geom_point() +
  geom_point(data = eval, col = "red", size = 2) +
  geom_line(data = preds) +
  viridis::scale_color_viridis()
```

```{r mmrmsep}
rmsep <- eval %>% 
  left_join(pars) %>% 
  ungroup() %>% 
  mutate(DBHpred = 10+alpha*Year/(beta+Year)) %>% 
  mutate(SEP = (DBH - DBHpred)^2) 
ggplot(rmsep, aes(sqrt(SEP))) +
  geom_boxplot() +
  coord_flip() +
  ggtitle(paste("RMSEP=", round(sqrt(mean(rmsep$SEP)), 2), "cm"))
```

```{r speciesmmtree, eval=F}
library(V.PhyloMaker)
splist <- growth %>% 
  dplyr::select(Family, Genus, species) %>% 
  unique() %>% 
  mutate(genus = Genus, family = Family) %>% 
  dplyr::select(species, genus, family)
tree <- phylo.maker(sp.list = splist, tree = GBOTB.extended, nodes = nodes.info.1, scenarios = "S3")
ape::write.tree(tree$scenario.3, "save/phylogeny_mm.tree")
```

```{r mmgrowthdata}
growth <- as.data.frame(summary(fit)$statistics) %>% 
  dplyr::select(Mean) %>% 
  rownames_to_column("parameter") %>% 
  separate(parameter, c("parameter", "ind"), convert = T) %>% 
  reshape2::dcast(ind ~ parameter, value.var = "Mean") %>% 
  left_join(dplyr::select(mdata, ind, idTree, Family, Genus, species)) %>% 
  left_join(vroom::vroom(file = "save/env_full.tsv"))
phylo <- ape::read.tree("save/phylogeny_mm.tree")
```

```{r }
lme4::lmer(log(beta) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), growth) %>% 
  sjPlot::tab_model(show.icc = F)
```

```{r }
m <- lme4::lmer(log(beta) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), 
                na.omit(dplyr::select(growth, Family, Genus, species, NCI, twi, beta)) %>% mutate(twi = ifelse(twi <= 0, 10^-6, twi)))
r2 <- partR2::partR2(m, partvars = c("log(NCI)", "log(twi+1)"), R2_type = "marginal", nboot = 10)
partR2::forestplot(r2, type = "R2", text_size = 10)
```

```{r }
ggplot(growth, aes(log(NCI), log(beta), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```

```{r }
ggplot(growth, aes(log(twi+1), log(beta), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```

```{r }
lme4::lmer(log(alpha) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), growth) %>% 
  sjPlot::tab_model(show.icc = F)
```

```{r }
m <- lme4::lmer(log(alpha) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), 
                na.omit(dplyr::select(growth, Family, Genus, species, NCI, twi, alpha)) %>% mutate(twi = ifelse(twi <= 0, 10^-6, twi)))
r2 <- partR2::partR2(m, partvars = c("log(NCI)", "log(twi+1)"), R2_type = "marginal", nboot = 10)
partR2::forestplot(r2, type = "R2", text_size = 10)
```

```{r }
ggplot(growth, aes(log(NCI), log(alpha), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```

```{r }
ggplot(growth, aes(log(twi+1), log(alpha), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```




```{r }
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(group_by(growth, species) %>% summarise(beta = mean(beta))) %>% 
  ggtree(aes(color = log(beta)), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  viridis::scale_color_viridis(expression(log(beta)))
```

```{r}
library(phylosignal)
library(adephylo)
library(ape)
library(phylobase)
p4d <- phylo4d(phylo,
               data.frame(species = gsub("_", " ", phylo$tip.label)) %>% 
                 left_join(group_by(growth, species) %>% summarise(alpha  = mean(alpha, na.rm = T), beta = mean(beta, na.rm = T))) %>% 
                 dplyr::select(-species))
```

```{r}
phyloSignal(p4d = p4d, method = "all") %>% 
  lapply(as.data.frame) %>% 
  lapply(rownames_to_column, "parameter") %>% 
  bind_rows(.id = "type") %>% 
  reshape2::melt(c("type", "parameter")) %>% 
  reshape2::dcast(parameter + variable ~ type) %>% 
  kable(caption = "Phylogenetic signal with different methods.")
```

```{r correlog, eval=F}
alpha.crlg <- phyloCorrelogram(p4d, trait = "alpha", ci.bs	= 100)
beta.crlg <- phyloCorrelogram(p4d, trait = "beta", ci.bs	= 100)
save(alpha.crlg, beta.crlg, file = "save/correlogs")
```

```{r}
load("save/correlogs")
plot(alpha.crlg, main="alpha phylogenetic correlogram")
```

```{r}
load("save/correlogs")
plot(beta.crlg, main="beta phylogenetic correlogram")
```

```{r lipamm}
beta.lipa <- lipaMoran(p4d)
```


```{r }
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(beta.lipa$p.value %>% 
              as.data.frame() %>% 
              rownames_to_column("species") %>% 
              mutate(species = gsub("_", " ", species)) %>% 
              dplyr::rename(alpha_pvalue = alpha, beta_pvalues = beta)) %>% 
  ggtree(aes(color = alpha_pvalue < 0.5), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  scale_color_manual("alpha p<0.05", values =  c("grey", "red", "grey"))
```

```{r }
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(beta.lipa$p.value %>% 
              as.data.frame() %>% 
              rownames_to_column("species") %>% 
              mutate(species = gsub("_", " ", species)) %>% 
              dplyr::rename(alpha_pvalue = alpha, beta_pvalues = beta)) %>% 
  ggtree(aes(color = beta_pvalues < 0.5), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  scale_color_manual("beta p<0.05", values =  c("grey", "red", "grey"))
```
