```{r microtopo, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# MicroTopo

## Functional traits

```{r dataan3}
# yhat <- vroom::vroom("data/microtopo/Y_hat_Paracou_microtopo_221022_freq.tsv") %>% 
#   dplyr::select(idTree, freq) %>% 
#   dplyr::rename(yhat = freq)
yhat <- vroom::vroom("data/microtopo/Y_hat_Paracou_microtopo_221022_freq.tsv") %>%
  dplyr::mutate(yhat = Mean/freq) %>% 
  dplyr::select(idTree, yhat)
betatwi <- vroom::vroom("data/microtopo/beta_estimate.tsv") %>% 
  mutate(species = paste(genus, species), betatwi = m) %>% 
  dplyr::select(species, betatwi)
phd <- bind_rows(
  vroom::vroom("data/Measures_Symphonia - AllTraits.tsv") %>% 
    mutate(Genus = "Symphonia") %>%
    rename(Species = Morphotype) %>%
    mutate(Species = ifelse(Species == "Indet.",
                            c("globulifera", "sp.1", "sp.1")[fct_recode(Bark, "globulifera" = "G",
                                                                        "sp.1" =  "S")], Species)),
  vroom::vroom("data/Measures_Eschweilera - AllTraits.tsv") %>%
    filter(!(Plot == 14 & SubPlot == 1 & TreeFieldNum == 760))
) %>% 
  mutate(species = paste(Genus, Species)) %>% 
  dplyr::select(species, idTree, SLA, LDMC, LT, LA, CC, brBT, brWD, brBD) %>% 
  left_join(yhat) %>% 
  filter(!is.na(yhat)) %>% 
  group_by(species, idTree) %>% 
  summarise_all(mean, na.rm =T)
hydro <- vroom::vroom("data/211124_TraitDatabase_species_means_updatedNames.csv") %>% 
  mutate(species = gsub("_", " ", spName.new)) %>% 
  dplyr::rename(LSWC = LSWC_E.per_corr_mean, RWC = RWC_E.per_corr_mean, Ptlp = ptlp_mean, d13C = d13C.per_mean, CN = C.N_mean,
                stomataD = stomata_density.mm2_mean, gmin = gmin.slope_mean, LWC = LWC_mean, LDMC = LDMC.mg.g_mean,
                N = N.per_mean, C = C.per_mean, P12stem = P12_stem.Mpa_mean, P50stem = P50_stem.MPa_mean, P88stem = P88_stem.MPa_mean,
                P12leaf = P12_leaf.MPa_mean, P50leaf = P50_leaf.MPa_mean, P88leaf = P88_leaf.MPa_mean) %>% 
  dplyr::select(species, LSWC, RWC, Ptlp, d13C, CN, stomataD, gmin, LWC, LDMC, N, C, P12stem, P50stem, P88stem, P12leaf, P50leaf, P88leaf) %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi))
fg <- readxl::read_xlsx("data/Appendix_S2-6___S8-13.xlsx", "App.S6-ok", skip = 3) %>% 
  mutate(species = gsub("_", " ", Species)) %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi)) %>% 
  dplyr::select(species, betatwi, Chlorophyll_content, Thickness, Toughness, Leaf_Area, SLA, C, N, `13C`, Ca, P, K, 
                Trunk_bark_thickness, Sapwood_WSG, WSG, Diameter, SRL, Tissue_density, SRTA, branchiness)
cam <- read_tsv("data/Ziegler2019 - All.tsv") %>% 
  dplyr::select(-Code) %>% 
  reshape2::melt("Species", variable.name = "Trait") %>% 
  mutate(value = gsub("− ", "-", value)) %>% 
  separate(value, c("mean", "sd"), "±", convert = T) %>% 
  mutate(mean = as.numeric(mean)) %>% 
  reshape2::dcast(Species ~ Trait, value.var = "mean") %>% 
  separate(Species, c("Genus", "Species", "Author")) %>% 
  select(-Author) %>% 
  mutate(species = paste(Genus, Species)) %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi))
santi <- read_delim("data/Santiago2018_S1.tsv", delim = " ", skip = 1,
           col_names = c("Genus", "Species", "WD", "X1", "X2",
                         "sapwood_saturated_water_content", "X3", "X4",
                         "sapwood_osmotic_potential_at_full_turgor", "X5", "X6",
                         "sapwood_water_potential_at_turgor_loss_point", "X7", "X8",
                         "total_sapwood_bulk_elastic_modulus", "X9", "X10",
                         "total_sapwood_relative_water_content_at_turgor_loss_point", "X11", "X12",
                         "sapwood_capacitance_at_full_turgor", "X13", "X14")) %>% 
  select(Genus, Species, sapwood_saturated_water_content, sapwood_osmotic_potential_at_full_turgor,
         sapwood_water_potential_at_turgor_loss_point, total_sapwood_bulk_elastic_modulus,
         total_sapwood_relative_water_content_at_turgor_loss_point, sapwood_capacitance_at_full_turgor) %>% 
  left_join(read_delim("data/Santiago2018_S2.tsv", delim = " ", skip = 1,
                       col_names = c("Genus", "Species", "WD", "X1", "X2",
                                     "P50", "X3", "X4",
                                     "slope_P50", "X5", "X6")) %>% 
              select(Genus, Species, P50, slope_P50)) %>% 
  mutate(Genus = recode(Genus, "B." = "Bocoa", "D." = "Dicorynia", "E." = "Eperua",
                        "J." = "Jacaranda", "L." = "Licania", "P." = "Pradosia", "S." = "Sextonia",
                        "T." = "Tachigali", "V." = "Vouacapoua")) %>% 
  mutate(Genus = ifelse(Species == "globulifera", "Symphonia", Genus)) %>% 
  mutate(Genus = ifelse(Species == "sagotiana", "Eschweilera", Genus)) %>% 
  mutate(Genus = ifelse(Species == "persistens", "Lecythis", Genus)) %>% 
  mutate(species = paste(Genus, Species)) %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi))
isa <- read_tsv("data/fec12452-sup-0002-appendixs1.csv") %>% 
  dplyr::select(Binomial, Pi_tlp) %>% 
  group_by(Binomial) %>% 
  summarise(Pi_tlp = mean(Pi_tlp)) %>% 
  separate(Binomial, c("Genus", "Species")) %>% 
  mutate(species = paste(Genus, Species)) %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi))
guillemot <- read_tsv("data/TAB_FINAL_GUILLEMOTetal.csv") %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi)) 
```

### All

```{r }
all_data <- bind_rows(
  phd %>% 
    mutate(dataset = "Schmitt et al., (2020)", response = "Y", response_value = yhat) %>% 
    dplyr::select(dataset, species, response, response_value, SLA, LDMC, LT, LA, CC) %>% 
    reshape2::melt(c("dataset", "species", "response", "response_value"), variable.name = "trait", value.name = "trait_value"),
  fg %>% 
    mutate(dataset = "Vleminckx et al., (2021)", response = "\\beta_{TWI}", response_value = betatwi) %>% 
    dplyr::select(-betatwi) %>% 
    reshape2::melt(c("dataset", "species", "response", "response_value"), variable.name = "trait", value.name = "trait_value"),
  cam %>% 
    mutate(dataset = "Ziegler et al., (2019)", response = "\\beta_{TWI}", response_value = betatwi) %>% 
    dplyr::select(-Species, -Genus, -betatwi) %>% 
    reshape2::melt(c("dataset", "species", "response", "response_value"), variable.name = "trait", value.name = "trait_value"),
  santi %>% 
    mutate(dataset = "Santiago et al., (2018)", response = "\\beta_{TWI}", response_value = betatwi, species = paste(Species, Genus)) %>% 
    dplyr::select(-Species, -Genus, -betatwi) %>% 
    reshape2::melt(c("dataset", "species", "response", "response_value"), variable.name = "trait", value.name = "trait_value"),
  isa %>% 
    mutate(dataset = "Maréchaux et al., (2015)", response = "\\beta_{TWI}", response_value = betatwi, species = paste(Species, Genus)) %>% 
    dplyr::select(-Species, -Genus, -betatwi) %>% 
    reshape2::melt(c("dataset", "species", "response", "response_value"), variable.name = "trait", value.name = "trait_value"),
  guillemot %>% 
    mutate(dataset = "Guillemot et al., (2022)", response = "\\beta_{TWI}", response_value = betatwi) %>% 
    dplyr::select(-genus, -family, -leaf_habit, -betatwi) %>% 
    reshape2::melt(c("dataset", "species", "response", "response_value"), variable.name = "trait", value.name = "trait_value")
) %>% na.omit() %>% 
  filter(!(trait %in% c("slope_P50", "branchiness", "branch_Psi12", "branch_Psi88", "HSM_Psimd_Psi88",
                        "branch_vulnerability_slope", "SMleaf", "HSM_Psimd2010_Psi12", "HSM_Psimd2010_Psi50",
                        "HSM_Psimd_Psi12", "HSM_PiTLP_Psi12", "total_sapwood_bulk_elastic_modulus"))) %>% 
  mutate(trait = recode(trait,
                        "P50"	= "xylem pressure inducing 50% loss of hydraulic conductance",			
                        "TLP"	= "leaf water potential at turgor loss point",				
                        "LMA"	= "leaf mass per area",				
                        "leaf_size"	= "leaf area",				
                        "Leaf_N"	= "leaf nitrogen content",				
                        "Leaf_P"	= "leaf phosphorus content",				
                        "Wood_density"	= "trunk wood specific gravity",					
                        "Seed_mass"	= "seed mass",				
                        "max_height"	= "maximum tree height",				
                        "Pi_tlp"	= "leaf water potential at turgor loss point",
                        "sapwood_saturated_water_content"	= "sapwood saturated water content",				
                        "sapwood_osmotic_potential_at_full_turgor"	= "sapwood osmotic potential at full turgor",				
                        "sapwood_water_potential_at_turgor_loss_point"	= "sapwood water potential at turgor loss point",				
                        "total_sapwood_relative_water_content_at_turgor_loss_point"	= "total sapwood relative water content at turgor loss_point",				
                        "sapwood_capacitance_at_full_turgor"	= "sapwood capacitance at full turgor",				
                        "SLA"	= "specific leaf area",				
                        "LDMC"	= "leaf dry matter content",				
                        "LT"	= "leaf thickness",
                        "LA"	= "leaf area",				
                        "CC"	= "chlorophyll content",				
                        "Chlorophyll_content"	= "chlorophyll content",				
                        "Thickness"	= "leaf thickness",				
                        "Toughness"	= "leaf thoughness",				
                        "Leaf_Area"	= "leaf area",				
                        "C"	= "leaf carbon content",				
                        "N"	= "leaf nitrogen content",				
                        "13C"	= "leaf delta 13C",				
                        "Ca"	= "leaf calcium content",	
                        "P"	= "leaf phosphorus content",				
                        "K"	= "leaf potassium content",				
                        "Trunk_bark_thickness"	= "trunk bark thickness",				
                        "Sapwood_WSG"	= "sapwood specific gravity",				
                        "WSG"	= "roots wood specific gravity",				
                        "Diameter"	= "fine roots diameter",				
                        "SRL"	= "specific root length",				
                        "Tissue_density"	= "fine roots tissue density",				
                        "SRTA"	= "specific root tip abundance",				
                        "HSM_PiTLP_Psi88"	= "hydraulic safety margin"))   
```

```{r }
all_reg <- all_data %>% 
  filter(trait != "gmax") %>% 
  group_by(dataset, response, trait) %>% 
  do(lm(scale(response_value) ~ scale(log(abs(trait_value))), data = .) %>% moderndive::get_regression_table()) %>% 
  filter(term != "intercept") %>% 
  dplyr::select(-term)   
```

```{r , fig.height=10, fig.width=8}
all_reg %>% 
  mutate(p_value = ifelse(p_value == 0, 10^-4, p_value)) %>%
  ggplot(aes(x = trait, y = estimate, alpha = p_value < 0.01, fill  = log10(p_value), label = trait)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = lower_ci, ymax = upper_ci), width = .2) +
  geom_hline(yintercept = 0, col = "black") +
  coord_flip() +
  facet_grid(dataset ~ ., scale = "free_y", space = "free_y") +
  viridis::scale_fill_viridis(expression(log[10](p[value])), direction = -1) +
  ylab("Standard estimate with confidence interval") +
  theme(strip.text.y = element_text(angle = 0), axis.title.y = element_blank(), legend.position = "bottom") +
  scale_alpha_discrete(guide = "none")  
```

### Interspecific

Based on Vleminckx et al., (2021).

```{r}
t <- all_data %>% 
  filter(dataset == "Vleminckx et al., (2021)") %>% 
  filter(trait %in% filter(all_reg, p_value < 0.01)$trait) %>% 
  group_by(species, trait) %>% 
  summarise(response_value = mean(response_value), trait_value = mean(trait_value)) %>% 
  reshape2::dcast(response_value + species ~ trait, value.var = "trait_value") %>% 
  na.omit() %>% 
  dplyr::select(-species) %>% 
  mutate_all(log) %>% 
  mutate_all(scale) %>% 
  dplyr::rename(betatwi = response_value)  
```

```{r}
lm(betatwi ~ ., data = t) %>%
  step(trace = F) %>%
  sjPlot::tab_model(show.icc = F)  
```

### Intraspecific

Based on Schmitt et al., (2020).

```{r}
t <- all_data %>% 
  filter(dataset == "Schmitt et al., (2020)") %>% 
  filter(trait %in% filter(all_reg, p_value < 0.01)$trait) %>% 
  group_by(species, trait) %>% 
  summarise(response_value = mean(response_value), trait_value = mean(trait_value)) %>% 
  reshape2::dcast(response_value + species ~ trait, value.var = "trait_value") %>% 
  na.omit() %>% 
  dplyr::select(-species) %>% 
  mutate_all(log) %>% 
  mutate_all(scale) %>% 
  dplyr::rename(yhat = response_value)  
```

```{r}
lm(scale(yhat) ~ ., data = t) %>%
  step(trace = F) %>%
  sjPlot::tab_model(show.icc = F)  
```

## Growth

### Interspecific

```{r}
betatwi <- vroom::vroom("data/microtopo/beta_estimate.tsv") %>% 
  mutate(species = paste(genus, species), betatwi = m) %>% 
  dplyr::select(species, betatwi)
growth <- vroom::vroom("save/growthfull.tsv") %>% 
  dplyr::select(species, gmax) %>% 
  group_by(species) %>% 
  summarise_all(mean, na.rm =T) %>% 
  left_join(betatwi) %>% 
  filter(!is.na(betatwi)) 
```

```{r}
lm(log(gmax) ~ betatwi, data = growth) %>%
  sjPlot::tab_model(show.icc = F) 
```

```{r}
ggplot(growth, aes(betatwi, gmax)) +
  geom_point() +
  scale_y_log10() +
  geom_smooth(method = "lm") +
  ylab(expression(Gmax[s]~cm.year^-1)) +
  xlab(expression(beta~TWI[s])) +
  ggtitle(expression(beta==0.11~p==0.002~R^2==0.075)) 
```

### Intraspecific

```{r}
yhat <- vroom::vroom("data/microtopo/Y_hat_Paracou_microtopo_221022_freq.tsv") %>%
  dplyr::mutate(yhat = Mean/freq) %>% 
  dplyr::select(idTree, yhat)
growth <- vroom::vroom("save/growthfull.tsv") %>% 
  dplyr::select(species, idTree, gmax) %>% 
  group_by(species) %>% 
  left_join(yhat) %>% 
  filter(!is.na(yhat)) 
```

```{r}
lm(log(gmax) ~ log(yhat), data = growth) %>%
  sjPlot::tab_model(show.icc = F) 
```

```{r}
ggplot(growth, aes(yhat, gmax)) +
  geom_point() +
  scale_y_log10() +
  scale_x_log10() +
  geom_smooth(method = "lm") +
  ylab(expression(Gmax[i]~cm.year^-1)) +
  xlab(expression(Y[i])) 
```
