```{r setupphylo, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(ggfortify)
library(ggtree)
library(phytools)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

# Phylogeny

**Work in progress.**

```{r phylodata}
load("save/gmax_greta_reduced.Rdata") 
data$Gmaxi <- mcmc_intervals_data(fit, pars = paste0("thetai[", 1:mdata$I, ",1]"))$m
data <- left_join(data, 
          data.frame(speciesNum = 1:mdata$S, 
                     Gmaxs = mcmc_intervals_data(fit, pars = paste0("thetai[", 1:mdata$S, ",1]"))$m))
rm(mdata, fit)
```

## Phylogeny

```{r speciesphylo, eval=F}
library(V.PhyloMaker)
splist <- data %>% 
  dplyr::select(Family, Genus, Species) %>% 
  unique() %>% 
  mutate(species = paste(Genus, Species), genus = Genus, family = Family) %>% 
  dplyr::select(species, genus, family)
tree <- phylo.maker(sp.list = splist, tree = GBOTB.extended, nodes = nodes.info.1, scenarios = "S3")
save(tree, splist, file = "save/phylogeny.Rdata")
```

```{r phylofig, fig.cap="Species phylogeny. The color indicate the median of the species growth potential (Gmaxs)."}
load("save/phylogeny.Rdata") 
fortify(tree$scenario.3) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(data) %>% 
  ggtree(aes(color = Gmaxs), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  viridis::scale_color_viridis(expression(Gmax[s]))
```

## Blomberg’s K

```{r BlombergK}
datab <- fortify(tree$scenario.3) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  left_join(unique(select(data, species, Gmaxs))) %>% 
  filter(!is.na(Gmaxs)) %>% 
  left_join(splist)
signal <- phylosig(tree$scenario.3, datab$Gmaxs, method="K", test=TRUE, nsim=999)
signal
```

## Variance partitioning

```{r lmm, fig.cap=" Variance partitioning of TWI effect across taxonomic levels. Variance partitioning was obtained using linear mixed models.", eval=F}
nlme::lme(log(Gmaxi) ~ 1, random=~1|Family/Genus/Species, data) %>% 
  ape::varcomp(scale = F, cum = F) %>% 
  as.vector() %>% 
  data.frame(level = c("Family", "Genus", "Species", "Individual"), variance = as.vector(.)) %>% 
  mutate(level = factor(level, levels = c("Family", "Genus", "Species", "Individual"))) %>% 
  mutate(pct = variance / sum(variance)*100) %>% 
  mutate(pct_text = paste0(round(pct), "%")) %>% 
  mutate(pct_text = gsub("^0%", "", pct_text)) %>% 
  ggplot(aes(x = 1, y = pct, fill = level)) +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(aes(y = pct, label = pct_text), col = "white", position = position_stack(vjust = .5)) +
  xlab("Trait") + ylab("Percentage of variance") +
  scale_x_discrete(labels = scales::parse_format()) +
  scale_color_discrete("") +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90), axis.title.x = element_blank())   
```
