```{r setupenv, include=FALSE}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F)
```

# Environment

**Work in progress.**

```{r NCI, eval=F}
load("save/gmax_greta_reduced.Rdata") 
rm(mdata, fit)
# parralelize with foreach
NC <- lapply(1:nrow(data), function(ind){
  src_sqlite("data/guyafor.sql") %>% 
    tbl("inventory") %>% 
    filter(Plot == local(data$Plot[ind])) %>% 
    filter(idTree != local(data$idTree[ind])) %>% 
    mutate(dij = sqrt((local(data$Xutm[ind]) - Xutm)^2+(local(data$Yutm[ind]) - Yutm)^2)) %>% 
    filter(dij < 20) %>% 
    mutate(DBH = CircCorr/pi) %>% 
    collect() %>% 
    group_by(CensusYear) %>% 
    summarise(NCI = sum(DBH*DBH*exp(-0.25*dij))) %>% 
    ungroup() %>% 
    summarise(idTree = local(data$idTree[ind]),
              NCI = mean(NCI))
  })
NC <- bind_rows(NC)
# add TWI
write_tsv(NC, file = "save/env.tsv")
```

```{r envdata}
load("save/gmax_greta_reduced.Rdata") 
data$Gmaxi <- mcmc_intervals_data(fit, pars = paste0("thetai[", 1:mdata$I, ",1]"))$m
data <- left_join(data, 
          data.frame(speciesNum = 1:mdata$S, 
                     Gmaxs = mcmc_intervals_data(fit, pars = paste0("thetai[", 1:mdata$S, ",1]"))$m))
data <- data %>% 
  left_join(read_tsv(file = "save/env.tsv"))
rm(mdata, fit)
```

```{r}
ggplot(data, aes(log(NCI), log(Gmaxi), col = species)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
lm(log(Gmaxi) ~ Family + Genus + species + log(NCI), data) %>% 
  sjPlot::tab_model()
```

```{r}
data.frame(level = c("Family", "log(NCI)", "Residual"), variance = anova(lm(log(Gmaxi) ~ Family + Genus + species + log(NCI), data))$`Sum Sq`) %>% 
    mutate(level = factor(level, levels = c("Family", "log(NCI)", "Residual"))) %>% 
  mutate(pct = variance / sum(variance)*100) %>% 
  mutate(pct_text = paste0(round(pct), "%")) %>% 
  mutate(pct_text = gsub("^0%", "", pct_text)) %>% 
  ggplot(aes(x = 1, y = pct, fill = level)) +
  geom_bar(stat = "identity", position = "stack") +
  geom_text(aes(y = pct, label = pct_text), col = "white", position = position_stack(vjust = .5)) +
  xlab("Trait") + ylab("Percentage of variance") +
  scale_x_discrete(labels = scales::parse_format()) +
  scale_color_discrete("") +
  theme(legend.position = "bottom", axis.text.x = element_text(angle = 90), axis.title.x = element_blank())   
```
