```{r analyses, include=FALSE, eval=T}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(knitr)
library(tidyverse)
library(bayesplot)
library(greta)
library(ggtree)
theme_set(bayesplot::theme_default())
opts_chunk$set(
  echo = F, message = F, warning = F, fig.height = 6, fig.width = 8,
  cache = T, cache.lazy = F, eval=T)
```

# Analyses

In this chapter we ...

```{r env, eval=F}
rm(list = ls()) ; invisible(gc()) ; set.seed(42)
library(parallel)
library(doSNOW)
library(foreach)
library(tidyverse)
load("save/gmax_greta_full.Rdata") 
rm(mdata, fit)
cl <- makeCluster(30, outfile = "/dev/null")
registerDoSNOW(cl)
pb <- txtProgressBar(max = nrow(data), style = 3)
progress <- function(n) setTxtProgressBar(pb, n)
opts <- list(progress = progress)
NC <- foreach(ind=1:nrow(data),
              .packages = "dplyr",
              .options.snow = opts) %dopar% {
                con <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
                NC <- tbl(con, "inventory") %>% 
                  filter(Plot == local(data$Plot[ind])) %>% 
                  filter(idTree != local(data$idTree[ind])) %>% 
                  mutate(dij = sqrt((local(data$Xutm[ind]) - Xutm)^2+(local(data$Yutm[ind]) - Yutm)^2)) %>% 
                  filter(dij < 20) %>% 
                  mutate(DBH = CircCorr/pi) %>% 
                  collect() %>% 
                  group_by(CensusYear) %>% 
                  summarise(NCI = sum(DBH*DBH*exp(-0.25*dij))) %>% 
                  ungroup() %>% 
                  summarise(idTree = local(data$idTree[ind]),
                            NCI = mean(NCI))
                DBI::dbDisconnect(con)
                return(NC)
              } 
close(pb)
stopCluster(cl)
NC <- bind_rows(NC)
guyafor <- DBI::dbConnect(RSQLite::SQLite(), dbname = "data/guyafor.sql")
trees <- tbl(guyafor, "inventory") %>% 
  filter(Forest == "Paracou") %>% 
  dplyr::select(idTree, Xutm, Yutm) %>% 
  collect() %>% 
  unique()
DBI::dbDisconnect(guyafor) ; rm(guyafor)
XY <- NC %>% 
  left_join(trees) %>% 
  sf::st_as_sf(coords = c("Xutm", "Yutm"),
             crs = '+proj=utm +zone=22 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0')
NC$twi <- raster::extract(raster::raster("data/TWI_1m.tif"), XY)
write_tsv(NC, file = "save/env_full.tsv")
```

```{r phylo, eval=F}
library(V.PhyloMaker)
splist <- growth %>% 
  dplyr::select(Family, Genus, species) %>% 
  unique() %>% 
  mutate(genus = Genus, family = Family) %>% 
  dplyr::select(species, genus, family)
tree <- phylo.maker(sp.list = splist, tree = GBOTB.extended, nodes = nodes.info.1, scenarios = "S3")
ape::write.tree(tree$scenario.3, "save/phylogeny_mm.tree")
```

```{r dataan, eval=F }
load("save/mdata.Rdata")
load("save/gompertzsum2.Rdata")  
pars <- as.data.frame(fit_gompertzsum2, pars = c('gmax', "dopt", "ks")) %>% 
  reshape2::melt(variable.name = "parameter") %>% 
  group_by(parameter) %>% 
  summarise(value = median(value)) %>% 
  separate(parameter, c("parameter", "ind"), convert = T) %>% 
  reshape2::dcast(ind ~ parameter)
growth <- pars %>% 
  left_join(dplyr::select(mdata, ind, idTree, Family, Genus, species)) %>% 
  left_join(vroom::vroom(file = "save/env_full.tsv")) %>% 
  unique()
phylo <- ape::read.tree("save/phylogeny_mm.tree")
```

```{r , eval=F}
lme4::lmer(log(gmax) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), growth) %>% 
  sjPlot::tab_model(show.icc = F)
```

```{r , eval=F}
m <- lme4::lmer(log(gmax) ~ log(NCI) + log(twi+1) + (1  | Family/Genus/species), 
                na.omit(dplyr::select(growth, Family, Genus, species, NCI, twi, gmax)) %>% mutate(twi = ifelse(twi <= 0, 10^-6, twi)))
r2 <- partR2::partR2(m, partvars = c("log(NCI)", "log(twi+1)"), R2_type = "marginal", nboot = 10)
partR2::forestplot(r2, type = "R2", text_size = 10)
```

```{r , eval=F}
ggplot(growth, aes(log(NCI), log(gmax), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```

```{r , eval=F}
ggplot(growth, aes(log(twi+1), log(gmax), col = species)) +
  geom_point() +
  geom_smooth(method = "lm", aes(group = NA)) +
  scale_color_discrete(guide = "none")
```

```{r , eval=F}
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(group_by(growth, species) %>% summarise(gamma = mean(gamma))) %>% 
  ggtree(aes(color = log(gamma)), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  viridis::scale_color_viridis(expression(log(gamma)))
```

```{r , eval=F}
library(phylosignal)
library(adephylo)
library(ape)
library(phylobase)
p4d <- phylo4d(phylo,
               data.frame(species = gsub("_", " ", phylo$tip.label)) %>% 
                 left_join(group_by(growth, species) %>% summarise(alpha  = mean(alpha, na.rm = T), gamma = mean(gamma, na.rm = T))) %>% 
                 dplyr::select(-species))
```

```{r , eval=F}
phyloSignal(p4d = p4d, method = "all") %>% 
  lapply(as.data.frame) %>% 
  lapply(rownames_to_column, "parameter") %>% 
  bind_rows(.id = "type") %>% 
  reshape2::melt(c("type", "parameter")) %>% 
  reshape2::dcast(parameter + variable ~ type) %>% 
  kable(caption = "Phylogenetic signal with different methods.")
```

```{r correlog, eval=F}
gamma.crlg <- phyloCorrelogram(p4d, trait = "gamma", ci.bs	= 100)
save(gamma.crlg, file = "save/correlogs")
load("save/correlogs")
plot(gamma.crlg, main="gamma phylogenetic correlogram")
```

```{r lipa, eval=F}
lipa <- lipaMoran(p4d)
fortify(phylo) %>% 
  mutate(species = gsub("_", " ", label)) %>%
  mutate(label = species) %>% 
  left_join(lipa$p.value %>% 
              as.data.frame() %>% 
              rownames_to_column("species") %>% 
              mutate(species = gsub("_", " ", species)) %>% 
              dplyr::rename(alpha_pvalue = alpha, gamma_pvalues = gamma)) %>% 
  ggtree(aes(color = gamma_pvalues < 0.5), layout="circular") + 
  geom_tiplab2(size = 2) +
  theme_tree(legend.position='right', legend.text = element_text(face = "italic")) +
  scale_alpha_manual("taxon", values = c(0.2, 1)) +
  scale_size_manual("taxon", values = c(1, 2)) +
  scale_color_manual("gamma p<0.05", values =  c("grey", "red", "grey"))
```
